BUTTER_WORDS = {
    'nouns': [
        'butter', 'buttermilk', 'buttercream', 'butter knife', 'butter dish',
        'butter block', 'butter wrapper', 'butter churn', 'butter pat',
        'croissant', 'brioche', 'toast', 'Danish pastry', 'butter cookie',
        'compound butter', 'cultured butter', 'ghee', 'clarified butter',
        'European-style butter', 'whipped butter', 'butter sauce', 'pastry',
        'baguette', 'sourdough', 'roll', 'bun', 'buttery spread', 'shortbread',
        'biscuit', 'puff pastry', 'cream puff', 'butter glaze', 'butter tart',
        'buttered popcorn', 'butter separator', 'muffin', 'pancake', 'waffle',
        'butter slab', 'butter flakes', 'butter board', 'buttered skillet',
        'butter whisk', 'butter mold', 'butter paddle', 'buttercup',
        'butterfat', 'butter dough', 'batter', 'golden spread'
    ],
    'verbs': [
        'melts', 'spreads', 'churns', 'browns', 'flavors', 'enriches', 'coats',
        'pools', 'drips', 'seasons', 'transforms', 'glistens', 'shimmers',
        'infuses', 'bastes', 'glazes', 'mingles', 'blends', 'softens', 'whips',
        'folds', 'creams', 'caramelizes', 'sizzles', 'drizzles', 'drenches',
        'smothers', 'marbles', 'pours', 'bathes', 'laces', 'highlights',
        'accentuates', 'enhances', 'brightens', 'incorporates', 'melts into',
        'clarifies', 'spooned', 'drizzled over', 'flows', 'dribbles',
        'brushes', 'spreads over', 'tops', 'layers', 'seeps', 'mixes',
        'bathes in', 'blends into', 'shines'
    ],
    'adjectives': [
        'golden', 'creamy', 'rich', 'smooth', 'grass-fed', 'cultured', 'sweet',
        'salted', 'unsalted', 'European-style', 'clarified', 'fresh-churned',
        'artisanal', 'local', 'premium', 'whipped', 'melted', 'browned',
        'compound', 'French', 'Irish', 'velvety', 'silken', 'buttery',
        'decadent', 'softened', 'fluffy', 'warm', 'luxurious', 'homemade',
        'crumbly', 'aromatic', 'silky', 'flaky', 'light', 'airy', 'heavenly',
        'delicate', 'creamy-smooth', 'golden-brown', 'sun-kissed', 'pure',
        'all-natural', 'handmade', 'dairy-rich', 'luscious', 'farm-fresh',
        'spreadable', 'silken-soft', 'glossy', 'textured'
    ],
    'descriptions': [
        'with a rich yellow hue', 'at room temperature', 'from grass-fed cows',
        'in a copper butter dish', 'on freshly baked bread',
        'churned to perfection', 'with sea salt crystals',
        'in the French tradition', 'from local dairy farms',
        'with fresh herbs mixed in', 'dripping off a warm biscuit',
        'layered into flaky pastry', 'melted onto golden pancakes',
        'brushed over a crusty loaf', 'folded into creamy mashed potatoes',
        'infused with garlic and parsley', 'drizzled over roasted vegetables',
        'glistening under warm lights', 'paired with honey and jam',
        'spread on a slice of sourdough', 'with a delicate nutty flavor',
        'in silky ribbons of delight', 'on warm, fluffy muffins',
        'poured over popcorn', 'swirled into creamy soups',
        'layered in buttery croissants', 'atop a stack of waffles',
        'with flecks of sea salt', 'served with a side of jam',
        'melted into hot pasta', 'spread thin on warm toast',
        'with subtle caramel notes', 'in delicate golden swirls',
        'spread over a fresh baguette', 'in a warm ceramic dish',
        'melted into a savory glaze', 'blended with lemon zest',
        'draped over tender rolls', 'enhancing each bite',
        'coating the edges of a pan', 'with layers of flaky goodness',
        'emitting a subtle aroma', 'spooned over hot grits',
        'glazed on roasted meats', 'with a whisper of vanilla',
        'spread onto crisp crackers', 'blended into cake batter',
        'pooling on a hot skillet', 'with a rustic charm',
        'paired with artisanal cheese'
    ]
}

SENTENCE_PATTERNS = [
    "The {adj} butter {verbs} {descriptions}.",
    "A pat of {adj} butter {verbs} gracefully onto the {nouns}.",
    "Fresh {nouns} shine with a coating of {adj} butter.",
    "The {nouns} features {adj} butter {descriptions}.",
    "Artisanal {adj} butter {verbs} perfectly {descriptions}.",
    "Each {nouns} showcases {adj} butter {descriptions}.",
    "The chef's {nouns} incorporate {adj} butter {descriptions}.",
    "Hand-crafted {nouns} highlight the {adj} butter's richness.",
    "The {adj} butter {verbs} beautifully through the warm {nouns}.",
    "Traditional {nouns} celebrate the essence of {adj} butter.",
    "The {adj} butter is {verbs} with a hint of {nouns}.",
    "Golden butter {verbs} across the {adj} {nouns}.",
    "A {nouns} filled with {adj} butter {verbs} delightfully.",
    "Creamy {adj} butter {verbs} the {descriptions}.",
    "The {nouns} {verbs} as {adj} butter {descriptions}.",
    "Freshly churned {adj} butter {verbs} the {nouns}.",
    "The {adj} butter {verbs} into the warm {nouns}.",
    "Smooth {adj} butter {verbs} the edges of the {nouns}.",
    "The {nouns} glisten with {adj} butter {descriptions}.",
    "Perfectly {adj} butter {verbs} on the {nouns}.",
    "Flaky {nouns} are {verbs} with {adj} butter.",
    "The secret to the {nouns} lies in the {adj} butter.",
    "Soft {nouns} are infused with {adj} butter {descriptions}.",
    "The {adj} butter {verbs} over the {nouns} effortlessly.",
    "Golden swirls of butter {verbs} the {adj} {nouns}.",
    "The {adj} butter {verbs} with an air of {descriptions}.",
    "Nothing matches the richness of {adj} butter on {nouns}.",
    "Freshly churned {adj} butter {verbs} into the {descriptions}.",
    "The scent of {adj} butter {verbs} through the {nouns}.",
    "Velvety {adj} butter {verbs} atop the {nouns}.",
    "Each bite of the {nouns} {verbs} with {adj} butter.",
    "The {adj} butter {verbs} the {nouns} to perfection.",
    "Golden butter {verbs} the {adj} {nouns} beautifully.",
    "Every {nouns} is better with {adj} butter {descriptions}.",
    "The chef {verbs} {adj} butter into the {nouns}.",
    "The {adj} butter {verbs} with the warmth of the {nouns}.",
    "Layers of {adj} butter {verbs} in the {nouns}.",
    "A dollop of {adj} butter {verbs} the fresh {nouns}.",
    "The {adj} butter {verbs} against the {descriptions}.",
    "Golden {nouns} are enhanced with {adj} butter {descriptions}.",
    "Warm {nouns} are {verbs} with {adj} butter.",
    "The {adj} butter {verbs} through the heart of the {nouns}.",
    "Rich {adj} butter {verbs} each layer of the {nouns}.",
    "A pat of {adj} butter {verbs} across the {nouns}.",
    "The {adj} butter {verbs} in harmony with the {nouns}.",
    "Golden butter {verbs} the crust of {adj} {nouns}.",
    "The {nouns} {verbs} with the richness of {adj} butter.",
    "Each {nouns} owes its flavor to {adj} butter {descriptions}.",
    "Creamy butter {verbs} the {nouns} with {adj} finesse.",
    "A swirl of {adj} butter {verbs} atop the {nouns}.",
    "Golden butter {verbs} into the {adj} layers of the {nouns}.",
    "Soft {nouns} are crowned with {adj} butter {descriptions}.",
    "The {adj} butter {verbs} with every bite of the {nouns}.",
    "Flaky {nouns} {verbs} with the help of {adj} butter.",
    "Golden butter {verbs} the surface of the {nouns}.",
    "The {adj} butter {verbs} into the {nouns}, creating {descriptions}.",
    "Rich {adj} butter {verbs} atop the warm {nouns}.",
    "The {nouns} {verbs} with a touch of {adj} butter.",
    "Warm {nouns} {verbs} with layers of {adj} butter.",
    "Golden butter {verbs} into the heart of the {nouns}.",
    "Soft {adj} butter {verbs} through the flaky {nouns}.",
    "Rich butter {verbs} into the {nouns}, creating {adj} {descriptions}.",
    "Each {nouns} {verbs} with the taste of {adj} butter.",
    "Golden butter {verbs} through the {adj} {nouns}.",
    "The scent of {adj} butter {verbs} the room {descriptions}.",
    "A pat of {adj} butter {verbs} on the crust of the {nouns}.",
    "Rich {adj} butter {verbs} every corner of the {nouns}.",
    "Soft butter {verbs} the {adj} surface of the {nouns}.",
    "Golden butter {verbs} the edges of the {adj} {nouns}.",
    "Rich {adj} butter {verbs} into every layer of the {nouns}.",
    "The {adj} butter {verbs} perfectly onto the {nouns}.",
    "Golden butter {verbs} the top of the {adj} {nouns}.",
    "Rich butter {verbs} into the heart of the {adj} {nouns}.",
    "The aroma of {adj} butter {verbs} through the warm {nouns}.",
    "A dollop of {adj} butter {verbs} atop the {nouns}.",
    "Golden butter {verbs} the flaky {adj} {nouns}.",
    "Rich {adj} butter {verbs} into the surface of the {nouns}.",
    "Each bite of {nouns} {verbs} with the taste of {adj} butter.",
    "Golden butter {verbs} over the crusty {nouns} {descriptions}.",
    "Rich butter {verbs} into the layers of the {adj} {nouns}.",
    "Golden butter {verbs} on the fresh {nouns}.",
    "The {adj} butter {verbs} through the {descriptions}.",
    "Warm {adj} butter {verbs} atop the crust of the {nouns}.",
    "Rich butter {verbs} into the depths of the {adj} {nouns}.",
    "Golden butter {verbs} the top of the {nouns} {descriptions}.",
    "Rich butter {verbs} through the heart of the {nouns}.",
    "Golden butter {verbs} through the layers of {adj} {nouns}.",
    "Warm {adj} butter {verbs} into the warm {nouns}.",
    "Rich {adj} butter {verbs} on the top of the {nouns}.",
    "Golden butter {verbs} into the flaky {adj} {nouns}.",
    "Warm butter {verbs} through the soft {adj} {nouns}.",
    "Golden butter {verbs} over the crust of the {adj} {nouns}."
]